version: '2'

services:
  node:
    env_file: .env
    container_name: be
    image: 'node:16.13.0'
    user: 'node'
    working_dir: /home/node/app/dist
    environment:
      NODE_ENV: production
      HOST: '${BE_HOST}'
      PORT: '${BE_PORT}'
      MONGO_URL: 'mongodb://db:27017'
      MONGO_DATABASE: '${MONGO_DATABASE-tm-ks}'
    volumes:
      - ./be:/home/node/app
    ports:
      - '8080:8080'
    command: 'npm run build:start'
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
