version: '2'

services:
  knowledge-store:
    env_file: .env
    image: 'node:lts-alpine'
    user: 'node'
    working_dir: /home/node/app/dist
    environment:
      NODE_ENV: production
      HOST: '${BE_HOST}'
      PORT: '${BE_PORT}'
      MONGO_HOST: 'mongo'
    volumes:
      - ./be:/home/node/app
    ports:
      - '8080:8080'
    command: 'npm run dev:start'
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
