version: '2'

services:
  knowledge-store:
    env_file: .env
    image: 'node:lts-alpine'
    user: 'node'
    working_dir: /home/node/app/dist
    volumes:
      - ./be:/home/node/app
    ports:
      - '8080:8080'
    command: 'npm run build:start'
  mongo:
    image: mongo:latest
    environment:
      MONGO_DATABASE: '${MONGO_DATABASE-knowledge}'
    ports:
      - "27017:27017"
