version: '3.8'

services:
  knowledge-store:
    env_file: .env
    image: 'node:lts-alpine'
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      HOST: '${BE_HOST}'
      PORT: '${BE_PORT}'
      MONGO_HOST: 'mongo'
    volumes:
      - ./be:/home/node/app
      - ./openapi.yaml:/home/node/openapi.yaml
    ports:
      - '8080:8080'
    command: 'npm run dev:start'
  mongo:
    image: mongo:4.4.12 # Last 4.x, latest image is 5+ incompatible with mongodb k8s version
    volumes:
      - ./be/mongodb-create-user.sh:/docker-entrypoint-initdb.d/mongodb-create-user.sh
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/${MONGO_DB_DATABASE} --quiet
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
  vuejs:
    env_file: .env
    image: 'node:lts-alpine'
    user: 'node'
    working_dir: /app
    environment:
      HOST: '${BE_HOST}'
      PORT: '${BE_PORT}'
      MONGO_HOST: 'mongo'
    volumes:
      - ./fe:/app
    ports:
      - '4200:4200'
    command: 'npm run docker:start'
