name: Lint, Test, and Build
on:  [push, pull_request, workflow_dispatch]
jobs:
  Lint:
    defaults:
      run:
        working-directory: ./be
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint BE
        run: npm run lint
  Test:
    defaults:
      run:
        working-directory: ./be
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test BE
        run: cd be && npm run test´
  Build:
    defaults:
      run:
        working-directory: ./be
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build BE
        run: cd be && npm run build
  FE-Lint-Test-Build:
    defaults:
      run:
        working-directory: ./fe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TODO Lint, Test, and Build FE wich caching
        run: echo "TODO Lint, Test, and Build FE wich caching"
